language: scala
jdk:
- openjdk6
scala:
- 2.10.3
services:
- postgresql
env:
- DATABASE_URL=postgres://myleavingapp:myleavingapp@localhost/myleavingapp
before_script:
- psql -c 'create database myleavingdo;' -U postgres
script: sbt test
deploy:
  provider: heroku
  api_key:
    secure: JUhXoidCYC3o+Z0uFP7VKHc9IWc/SdZOF8CkYHMIscFvE5vdWxG2j7KgVrwg4F8/ZGmoqq0htBGqVRmXytvXqsP3cm2bX+Godt1xozAAeLrLI5lw8SRWI+a92WXQPX34ZBssjlHJQTvDDDSn3eNBqKq7VMw8swHYW9cN4CMCoQk=
  app: myleavingdosurvey 
  on:
    repo: paulspencerwilliams/myLeavingDoSurvey
